project:
  type: website
  output-dir: docs
  title: "Vandalizer Wiki"
  post-render:
  - cp data/issues.json docs/issues.json
  - cp -r test-files docs/test-files

website:
  title: "Vandalizer Wiki"
  page-navigation: true
  repo-url: https://github.com/ui-insight/vandalizer-manual
  repo-actions: [edit]
  sidebar:
    style: "floating"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Disclaimer"
        href: disclaimer.qmd
      - text: "Introduction"
        href: introduction.qmd
      - text: "Security & Privacy"
        href: security.qmd
      - text: "Interface"
        href: interface.qmd
      - text: "Tasks"
        href: tasks.qmd
      - text: "Workflows"
        href: workflows.qmd
      - text: "Global Tasks"
        href: global-tasks.qmd
      - text: "Share Workflows"
        href: share-workflows.qmd
      - text: "Examples"
        href: example.qmd
      - text: "Issue Tracker"
        href: issue-tracker.qmd
      - text: "NCURA Workshop"
        href: ncura1.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    toc-location: left
    number-sections: false
